apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo-repo
        namespace: flux-system
      version: "6.3.5"
  values:
    replicaCount: "${REPLICA_COUNT:-2}"
    image:
      repository: "${IMAGE_REPOSITORY:-ghcr.io/stefanprodan/podinfo}"
      tag: "${IMAGE_TAG:-6.3.5}"
